### PR TITLE
Support  for `--listEmittedFiles` + new message `file_emitted`

### PR DESCRIPTION
**Pull request by pp0rtal**
Issue: https://github.com/gilamran/tsc-watch/issues/138 read for more
What does this PR:

- Handle `--listEmittedFiles` param and call `tsc` accordingly
- Update `tsc-watch` to send `file_emitted:<filepath>`
- Make client emit `file_emitted:` with the `<filePath>`

I've put grey color because TSFILE are not very important see
Screenshot from 2022-03-10 11-20-08

(Tests are passing)
Screenshot from 2022-03-10 14-26-22

### CODE REVIEW

**Comment by gilamran** [comment]
@pp0rtal I think that there's an overall issue with this PR.
As typescript itself supports `--listEmittedFiles` we shouldn't pass it as an argument (it's done automatically) and we shouldn't alter the output, we only have to send a signal with this info...

wdyt?

**Comment by pp0rtal** [comment]
@gilamran Sure! 

You're right, it's a native param, so I just dropped my commit cac45e98f826b9c098d5f971ad7eef48d9325c11 and force push for clarity.
_(and I removed `--listEmittedFiles` my addition in `newAdditionToSyntax`, and in the README, commits are updated)_

>  and we shouldn't alter the output, we only have to send a signal with this info...

I'm not altering the output, I'm colorizing it. That's what is done for a few commands, and users can still use `--noColors` right?
My rationale: I'm currently using `--noClear`, I want `file_emitted` events, but actually I don't care much about the output :neutral_face: 
I've seen you don't alter, that's why I'm at least adding colors.

Of course, I can do what suits you the best, should I just remove color support?

**Comment by gilamran** [comment]
@pp0rtal I've created a branch on my repo with most of your changes: https://github.com/gilamran/tsc-watch/tree/feat-emitted-files
Please review.

Thanks!

**Comment by pp0rtal** [comment]
@gilamran Only minor comments fadd79e1c3bb50cb1319f4333ac1c27519aa2d09 excepts the `split`,
because I know it will lead to real bugs (I've some `:` in my codebase!).
Except this one comment I'm **OK to your version**. Thanks for your investment here! :+1:

**Comment by gilamran** [comment]
@pp0rtal I've made some changes and pushed to the branch, please give it a try, and let me know. I'll publish it

**Comment by pp0rtal** [comment]
@gilamran Just checked a78bc970c7423c9ec58f12077a3ab8e2279925ad and tried the sources for real, it works fine :+1: 
Good to go :)

**Pull request merged**
